# Build step #1: build the React front end
FROM node:18 as build-step
WORKDIR /frontend
ENV PATH /frontend/node_modules/.bin:$PATH
COPY frontend/package.json frontend/yarn.lock frontend/tsconfig.json frontend/webpack.config.js ./
COPY frontend/src ./src
COPY frontend/public ./public
RUN yarn install
RUN yarn build --production

# Build step #2: build an nginx container
FROM nginx:stable-alpine
COPY --from=build-step /frontend/build /usr/share/nginx/html
COPY deployment/nginx.default.conf /etc/nginx/conf.d/default.conf