services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    image: codex-frontend-api
    ports:
      - "5000:5000"
    network_mode: "host"
  client:
    build:
      context: .
      dockerfile: Dockerfile.client
    image: codex-frontend-client
    ports:
      - "3000:80"
